/**
 * Typed re-export of the fitted outcome coefficients generated by
 * `deno task sim:refit`. The artifact JSON is the source of truth; this
 * module just narrows its types for synthesize-run-outcome and, in PR 3,
 * synthesize-pass-outcome.
 */
import type {
  PassCoefficients,
  RunCoefficients,
} from "./calibration/fit-outcomes.ts";
import artifact from "./calibration/outcome-coefficients.json" with {
  type: "json",
};

interface CoefficientsArtifact {
  pass: PassCoefficients;
  run: RunCoefficients;
}

const typed = artifact as unknown as CoefficientsArtifact;

export const PASS_COEFFICIENTS: PassCoefficients = typed.pass;
export const RUN_COEFFICIENTS: RunCoefficients = typed.run;
