/**
 * Public-facing names for the offensive and defensive scheme archetypes
 * generated by the coaches generator. Kept in shared so both server
 * (when populating candidate summaries) and client (when rendering the
 * Scheme column on the hiring tab) reference the same vocabulary.
 *
 * The string keys must stay aligned with the archetype names in
 * `server/features/coaches/coach-tendency-archetypes.ts`. The display
 * label is the tl;dr the GM sees in the hiring market — short, real
 * football lingo, no internal jargon.
 */

export const OFFENSIVE_ARCHETYPE_NAMES = [
  "shanahan_wide_zone",
  "air_raid",
  "spread_rpo",
  "pro_style_timing",
  "vertical_shot",
] as const;

export type OffensiveArchetypeName = typeof OFFENSIVE_ARCHETYPE_NAMES[number];

export const DEFENSIVE_ARCHETYPE_NAMES = [
  "fangio_two_high",
  "multiple_pattern_match",
  "blitz_heavy_press_man",
  "cover_three_base",
  "tampa_two_zone",
] as const;

export type DefensiveArchetypeName = typeof DEFENSIVE_ARCHETYPE_NAMES[number];

const OFFENSIVE_LABELS: Record<OffensiveArchetypeName, string> = {
  shanahan_wide_zone: "Wide Zone",
  air_raid: "Air Raid",
  spread_rpo: "Spread RPO",
  pro_style_timing: "Pro Style",
  vertical_shot: "Vertical Shot",
};

const DEFENSIVE_LABELS: Record<DefensiveArchetypeName, string> = {
  fangio_two_high: "Fangio Two-High",
  multiple_pattern_match: "Multiple Pattern-Match",
  blitz_heavy_press_man: "Press Man Blitz",
  cover_three_base: "Cover-3 Base",
  tampa_two_zone: "Tampa 2",
};

export function offensiveArchetypeLabel(name: string | null): string | null {
  if (!name) return null;
  return OFFENSIVE_LABELS[name as OffensiveArchetypeName] ?? name;
}

export function defensiveArchetypeLabel(name: string | null): string | null {
  if (!name) return null;
  return DEFENSIVE_LABELS[name as DefensiveArchetypeName] ?? name;
}
