CREATE TABLE "states" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"region" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "states_code_unique" UNIQUE("code"),
	CONSTRAINT "states_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "cities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"state_id" uuid NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cities_name_state_id_unique" UNIQUE("name","state_id")
);
--> statement-breakpoint
ALTER TABLE "cities" ADD CONSTRAINT "cities_state_id_states_id_fk" FOREIGN KEY ("state_id") REFERENCES "public"."states"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
INSERT INTO "states" ("code", "name", "region") VALUES
  ('AL', 'Alabama', 'South'),
  ('AK', 'Alaska', 'West'),
  ('AZ', 'Arizona', 'West'),
  ('AR', 'Arkansas', 'South'),
  ('CA', 'California', 'West'),
  ('CO', 'Colorado', 'West'),
  ('CT', 'Connecticut', 'Northeast'),
  ('DE', 'Delaware', 'South'),
  ('DC', 'District of Columbia', 'South'),
  ('FL', 'Florida', 'South'),
  ('GA', 'Georgia', 'South'),
  ('HI', 'Hawaii', 'West'),
  ('ID', 'Idaho', 'West'),
  ('IL', 'Illinois', 'Midwest'),
  ('IN', 'Indiana', 'Midwest'),
  ('IA', 'Iowa', 'Midwest'),
  ('KS', 'Kansas', 'Midwest'),
  ('KY', 'Kentucky', 'South'),
  ('LA', 'Louisiana', 'South'),
  ('ME', 'Maine', 'Northeast'),
  ('MD', 'Maryland', 'South'),
  ('MA', 'Massachusetts', 'Northeast'),
  ('MI', 'Michigan', 'Midwest'),
  ('MN', 'Minnesota', 'Midwest'),
  ('MS', 'Mississippi', 'South'),
  ('MO', 'Missouri', 'Midwest'),
  ('MT', 'Montana', 'West'),
  ('NE', 'Nebraska', 'Midwest'),
  ('NV', 'Nevada', 'West'),
  ('NH', 'New Hampshire', 'Northeast'),
  ('NJ', 'New Jersey', 'Northeast'),
  ('NM', 'New Mexico', 'West'),
  ('NY', 'New York', 'Northeast'),
  ('NC', 'North Carolina', 'South'),
  ('ND', 'North Dakota', 'Midwest'),
  ('OH', 'Ohio', 'Midwest'),
  ('OK', 'Oklahoma', 'South'),
  ('OR', 'Oregon', 'West'),
  ('PA', 'Pennsylvania', 'Northeast'),
  ('RI', 'Rhode Island', 'Northeast'),
  ('SC', 'South Carolina', 'South'),
  ('SD', 'South Dakota', 'Midwest'),
  ('TN', 'Tennessee', 'South'),
  ('TX', 'Texas', 'South'),
  ('UT', 'Utah', 'West'),
  ('VT', 'Vermont', 'Northeast'),
  ('VA', 'Virginia', 'South'),
  ('WA', 'Washington', 'West'),
  ('WV', 'West Virginia', 'South'),
  ('WI', 'Wisconsin', 'Midwest'),
  ('WY', 'Wyoming', 'West');
--> statement-breakpoint
INSERT INTO "cities" ("name", "state_id")
SELECT v.name, s.id
FROM (VALUES
  ('New York', 'NY'),
  ('Los Angeles', 'CA'),
  ('Chicago', 'IL'),
  ('Houston', 'TX'),
  ('Phoenix', 'AZ'),
  ('Philadelphia', 'PA'),
  ('San Antonio', 'TX'),
  ('San Diego', 'CA'),
  ('Dallas', 'TX'),
  ('Jacksonville', 'FL'),
  ('Fort Worth', 'TX'),
  ('San Jose', 'CA'),
  ('Austin', 'TX'),
  ('Charlotte', 'NC'),
  ('Columbus', 'OH'),
  ('Indianapolis', 'IN'),
  ('San Francisco', 'CA'),
  ('Seattle', 'WA'),
  ('Denver', 'CO'),
  ('Oklahoma City', 'OK'),
  ('Nashville', 'TN'),
  ('Washington', 'DC'),
  ('El Paso', 'TX'),
  ('Las Vegas', 'NV'),
  ('Boston', 'MA'),
  ('Detroit', 'MI'),
  ('Louisville', 'KY'),
  ('Portland', 'OR'),
  ('Memphis', 'TN'),
  ('Baltimore', 'MD'),
  ('Milwaukee', 'WI'),
  ('Albuquerque', 'NM'),
  ('Tucson', 'AZ'),
  ('Fresno', 'CA'),
  ('Sacramento', 'CA'),
  ('Atlanta', 'GA'),
  ('Mesa', 'AZ'),
  ('Kansas City', 'MO'),
  ('Raleigh', 'NC'),
  ('Colorado Springs', 'CO'),
  ('Omaha', 'NE'),
  ('Miami', 'FL'),
  ('Virginia Beach', 'VA'),
  ('Long Beach', 'CA'),
  ('Oakland', 'CA'),
  ('Minneapolis', 'MN'),
  ('Bakersfield', 'CA'),
  ('Tulsa', 'OK'),
  ('Tampa', 'FL'),
  ('Arlington', 'TX'),
  ('Aurora', 'CO'),
  ('Wichita', 'KS'),
  ('Cleveland', 'OH'),
  ('New Orleans', 'LA'),
  ('Henderson', 'NV'),
  ('Honolulu', 'HI'),
  ('Anaheim', 'CA'),
  ('Orlando', 'FL'),
  ('Lexington', 'KY'),
  ('Stockton', 'CA'),
  ('Riverside', 'CA'),
  ('Irvine', 'CA'),
  ('Corpus Christi', 'TX'),
  ('Newark', 'NJ'),
  ('Santa Ana', 'CA'),
  ('Cincinnati', 'OH'),
  ('Pittsburgh', 'PA'),
  ('Saint Paul', 'MN'),
  ('Greensboro', 'NC'),
  ('Jersey City', 'NJ'),
  ('Durham', 'NC'),
  ('Lincoln', 'NE'),
  ('North Las Vegas', 'NV'),
  ('Plano', 'TX'),
  ('Anchorage', 'AK'),
  ('Gilbert', 'AZ'),
  ('Madison', 'WI'),
  ('Reno', 'NV'),
  ('Chandler', 'AZ'),
  ('St. Louis', 'MO'),
  ('Chula Vista', 'CA'),
  ('Buffalo', 'NY'),
  ('Fort Wayne', 'IN'),
  ('Lubbock', 'TX'),
  ('St. Petersburg', 'FL'),
  ('Toledo', 'OH'),
  ('Laredo', 'TX'),
  ('Port St. Lucie', 'FL'),
  ('Glendale', 'AZ'),
  ('Irving', 'TX'),
  ('Winston-Salem', 'NC'),
  ('Chesapeake', 'VA'),
  ('Garland', 'TX'),
  ('Scottsdale', 'AZ'),
  ('Boise', 'ID'),
  ('Hialeah', 'FL'),
  ('Frisco', 'TX'),
  ('Richmond', 'VA'),
  ('Cape Coral', 'FL'),
  ('Norfolk', 'VA'),
  ('Spokane', 'WA'),
  ('Huntsville', 'AL'),
  ('Santa Clarita', 'CA'),
  ('Tacoma', 'WA'),
  ('Fremont', 'CA'),
  ('McKinney', 'TX'),
  ('San Bernardino', 'CA'),
  ('Baton Rouge', 'LA'),
  ('Modesto', 'CA'),
  ('Fontana', 'CA'),
  ('Salt Lake City', 'UT'),
  ('Moreno Valley', 'CA'),
  ('Des Moines', 'IA'),
  ('Worcester', 'MA'),
  ('Yonkers', 'NY'),
  ('Fayetteville', 'NC'),
  ('Sioux Falls', 'SD'),
  ('Grand Prairie', 'TX'),
  ('Rochester', 'NY'),
  ('Tallahassee', 'FL'),
  ('Little Rock', 'AR'),
  ('Amarillo', 'TX'),
  ('Overland Park', 'KS'),
  ('Columbus', 'GA'),
  ('Augusta', 'GA'),
  ('Mobile', 'AL'),
  ('Oxnard', 'CA'),
  ('Grand Rapids', 'MI'),
  ('Peoria', 'AZ'),
  ('Vancouver', 'WA'),
  ('Knoxville', 'TN'),
  ('Birmingham', 'AL'),
  ('Montgomery', 'AL'),
  ('Providence', 'RI'),
  ('Huntington Beach', 'CA'),
  ('Brownsville', 'TX'),
  ('Chattanooga', 'TN'),
  ('Fort Lauderdale', 'FL'),
  ('Tempe', 'AZ'),
  ('Akron', 'OH'),
  ('Glendale', 'CA'),
  ('Clarksville', 'TN'),
  ('Ontario', 'CA'),
  ('Newport News', 'VA'),
  ('Elk Grove', 'CA'),
  ('Cary', 'NC'),
  ('Aurora', 'IL'),
  ('Salem', 'OR'),
  ('Pembroke Pines', 'FL'),
  ('Eugene', 'OR'),
  ('Santa Rosa', 'CA'),
  ('Rancho Cucamonga', 'CA'),
  ('Shreveport', 'LA'),
  ('Garden Grove', 'CA'),
  ('Oceanside', 'CA'),
  ('Fort Collins', 'CO'),
  ('Springfield', 'MO'),
  ('Murfreesboro', 'TN'),
  ('Surprise', 'AZ'),
  ('Lancaster', 'CA'),
  ('Denton', 'TX'),
  ('Roseville', 'CA'),
  ('Palmdale', 'CA'),
  ('Corona', 'CA'),
  ('Salinas', 'CA'),
  ('Killeen', 'TX'),
  ('Paterson', 'NJ'),
  ('Alexandria', 'VA'),
  ('Hollywood', 'FL'),
  ('Hayward', 'CA'),
  ('Charleston', 'SC'),
  ('Macon', 'GA'),
  ('Lakewood', 'CO'),
  ('Sunnyvale', 'CA'),
  ('Kansas City', 'KS'),
  ('Springfield', 'MA'),
  ('Bellevue', 'WA'),
  ('Naperville', 'IL'),
  ('Tuscaloosa', 'AL'),
  ('Boone', 'NC'),
  ('Fayetteville', 'AR'),
  ('Jonesboro', 'AR'),
  ('USAF Academy', 'CO'),
  ('West Point', 'NY'),
  ('Auburn', 'AL'),
  ('Waco', 'TX'),
  ('Chestnut Hill', 'MA'),
  ('Bowling Green', 'OH'),
  ('Provo', 'UT'),
  ('Berkeley', 'CA'),
  ('Mount Pleasant', 'MI'),
  ('Clemson', 'SC'),
  ('Conway', 'SC'),
  ('Boulder', 'CO'),
  ('Storrs', 'CT'),
  ('Newark', 'DE'),
  ('Greenville', 'NC'),
  ('Ypsilanti', 'MI'),
  ('Boca Raton', 'FL'),
  ('Gainesville', 'FL'),
  ('Athens', 'GA'),
  ('Statesboro', 'GA'),
  ('Champaign', 'IL'),
  ('Bloomington', 'IN'),
  ('Iowa City', 'IA'),
  ('Ames', 'IA'),
  ('Jacksonville', 'AL'),
  ('Harrisonburg', 'VA'),
  ('Lawrence', 'KS'),
  ('Manhattan', 'KS'),
  ('Kennesaw', 'GA'),
  ('Kent', 'OH'),
  ('Lynchburg', 'VA'),
  ('Lafayette', 'LA'),
  ('Monroe', 'LA'),
  ('Ruston', 'LA'),
  ('Huntington', 'WV'),
  ('College Park', 'MD'),
  ('Amherst', 'MA'),
  ('Coral Gables', 'FL'),
  ('Oxford', 'OH'),
  ('Ann Arbor', 'MI'),
  ('East Lansing', 'MI'),
  ('Starkville', 'MS'),
  ('Oxford', 'MS'),
  ('Columbia', 'MO'),
  ('Annapolis', 'MD'),
  ('Las Cruces', 'NM'),
  ('Chapel Hill', 'NC'),
  ('DeKalb', 'IL'),
  ('Evanston', 'IL'),
  ('South Bend', 'IN'),
  ('Athens', 'OH'),
  ('Norman', 'OK'),
  ('Stillwater', 'OK'),
  ('Corvallis', 'OR'),
  ('University Park', 'PA'),
  ('West Lafayette', 'IN'),
  ('Piscataway', 'NJ'),
  ('Huntsville', 'TX'),
  ('University Park', 'TX'),
  ('Columbia', 'SC'),
  ('Hattiesburg', 'MS'),
  ('Stanford', 'CA'),
  ('Syracuse', 'NY'),
  ('College Station', 'TX'),
  ('San Marcos', 'TX'),
  ('Troy', 'AL'),
  ('Logan', 'UT'),
  ('Charlottesville', 'VA'),
  ('Blacksburg', 'VA'),
  ('Pullman', 'WA'),
  ('Morgantown', 'WV'),
  ('Bowling Green', 'KY'),
  ('Kalamazoo', 'MI'),
  ('Laramie', 'WY'),
  ('Abilene', 'TX'),
  ('Normal', 'AL'),
  ('Albany', 'NY'),
  ('Lorman', 'MS'),
  ('Pine Bluff', 'AR'),
  ('Daytona Beach', 'FL'),
  ('Smithfield', 'RI'),
  ('Lewisburg', 'PA'),
  ('San Luis Obispo', 'CA'),
  ('Buies Creek', 'NC'),
  ('Conway', 'AR'),
  ('New Britain', 'CT'),
  ('North Charleston', 'SC'),
  ('Hamilton', 'NY'),
  ('Ithaca', 'NY'),
  ('Hanover', 'NH'),
  ('Davidson', 'NC'),
  ('Dayton', 'OH'),
  ('Dover', 'DE'),
  ('Johnson City', 'TN'),
  ('Commerce', 'TX'),
  ('Charleston', 'IL'),
  ('Richmond', 'KY'),
  ('Cheney', 'WA'),
  ('Elon', 'NC'),
  ('Greenville', 'SC'),
  ('Boiling Springs', 'NC'),
  ('Grambling', 'LA'),
  ('Hampton', 'VA'),
  ('Cambridge', 'MA'),
  ('Moscow', 'ID'),
  ('Pocatello', 'ID'),
  ('Normal', 'IL'),
  ('Terre Haute', 'IN'),
  ('Jackson', 'MS'),
  ('Easton', 'PA'),
  ('Beaumont', 'TX'),
  ('Bethlehem', 'PA'),
  ('St. Charles', 'MO'),
  ('Brookville', 'NY'),
  ('Orono', 'ME'),
  ('Poughkeepsie', 'NY'),
  ('Lake Charles', 'LA'),
  ('North Andover', 'MA'),
  ('Itta Bena', 'MS'),
  ('West Long Branch', 'NJ'),
  ('Missoula', 'MT'),
  ('Bozeman', 'MT'),
  ('Morehead', 'KY'),
  ('Murray', 'KY'),
  ('Durham', 'NH'),
  ('Thibodaux', 'LA'),
  ('Florence', 'AL'),
  ('Grand Forks', 'ND'),
  ('Fargo', 'ND'),
  ('Flagstaff', 'AZ'),
  ('Greeley', 'CO'),
  ('Cedar Falls', 'IA'),
  ('Natchitoches', 'LA'),
  ('Prairie View', 'TX'),
  ('Clinton', 'SC'),
  ('Princeton', 'NJ'),
  ('Kingston', 'RI'),
  ('Moon Township', 'PA'),
  ('Fairfield', 'CT'),
  ('Loretto', 'PA'),
  ('Orangeburg', 'SC'),
  ('Vermillion', 'SD'),
  ('Brookings', 'SD'),
  ('Cape Girardeau', 'MO'),
  ('Hammond', 'LA'),
  ('Carbondale', 'IL'),
  ('Cedar City', 'UT'),
  ('Nacogdoches', 'TX'),
  ('DeLand', 'FL'),
  ('Easton', 'MA'),
  ('Stony Brook', 'NY'),
  ('Stephenville', 'TX'),
  ('Cookeville', 'TN'),
  ('Towson', 'MD'),
  ('Davis', 'CA'),
  ('Martin', 'TN'),
  ('St. George', 'UT'),
  ('Edinburg', 'TX'),
  ('Valparaiso', 'IN'),
  ('Villanova', 'PA'),
  ('Lexington', 'VA'),
  ('Ogden', 'UT'),
  ('Cullowhee', 'NC'),
  ('Macomb', 'IL'),
  ('Williamsburg', 'VA'),
  ('Spartanburg', 'SC'),
  ('New Haven', 'CT'),
  ('Youngstown', 'OH'),
  ('Green Bay', 'WI')
) AS v(name, code)
INNER JOIN "states" s ON s.code = v.code;
--> statement-breakpoint
ALTER TABLE "colleges" ADD COLUMN "city_id" uuid;
--> statement-breakpoint
UPDATE "colleges" c SET "city_id" = (
  SELECT ci.id FROM "cities" ci
  INNER JOIN "states" s ON ci.state_id = s.id
  WHERE ci.name = c.city AND s.code = c.state
);
--> statement-breakpoint
ALTER TABLE "colleges" ALTER COLUMN "city_id" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "colleges" ADD CONSTRAINT "colleges_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "colleges" DROP COLUMN "city";
--> statement-breakpoint
ALTER TABLE "colleges" DROP COLUMN "state";
--> statement-breakpoint
-- teams.city lacks state qualifier and cannot be unambiguously backfilled;
-- truncate teams (and FK-dependent rows) so we can re-seed them cleanly.
TRUNCATE "teams" RESTART IDENTITY CASCADE;
--> statement-breakpoint
ALTER TABLE "teams" DROP COLUMN "city";
--> statement-breakpoint
ALTER TABLE "teams" ADD COLUMN "city_id" uuid NOT NULL;
--> statement-breakpoint
ALTER TABLE "teams" ADD CONSTRAINT "teams_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE restrict ON UPDATE no action;

