CREATE TABLE "draft_prospect_attributes" (
	"draft_prospect_id" uuid PRIMARY KEY NOT NULL,
	"speed" smallint NOT NULL,
	"speed_potential" smallint NOT NULL,
	"acceleration" smallint NOT NULL,
	"acceleration_potential" smallint NOT NULL,
	"agility" smallint NOT NULL,
	"agility_potential" smallint NOT NULL,
	"strength" smallint NOT NULL,
	"strength_potential" smallint NOT NULL,
	"jumping" smallint NOT NULL,
	"jumping_potential" smallint NOT NULL,
	"stamina" smallint NOT NULL,
	"stamina_potential" smallint NOT NULL,
	"durability" smallint NOT NULL,
	"durability_potential" smallint NOT NULL,
	"arm_strength" smallint NOT NULL,
	"arm_strength_potential" smallint NOT NULL,
	"accuracy_short" smallint NOT NULL,
	"accuracy_short_potential" smallint NOT NULL,
	"accuracy_medium" smallint NOT NULL,
	"accuracy_medium_potential" smallint NOT NULL,
	"accuracy_deep" smallint NOT NULL,
	"accuracy_deep_potential" smallint NOT NULL,
	"accuracy_on_the_run" smallint NOT NULL,
	"accuracy_on_the_run_potential" smallint NOT NULL,
	"touch" smallint NOT NULL,
	"touch_potential" smallint NOT NULL,
	"release" smallint NOT NULL,
	"release_potential" smallint NOT NULL,
	"ball_carrying" smallint NOT NULL,
	"ball_carrying_potential" smallint NOT NULL,
	"elusiveness" smallint NOT NULL,
	"elusiveness_potential" smallint NOT NULL,
	"route_running" smallint NOT NULL,
	"route_running_potential" smallint NOT NULL,
	"catching" smallint NOT NULL,
	"catching_potential" smallint NOT NULL,
	"contested_catching" smallint NOT NULL,
	"contested_catching_potential" smallint NOT NULL,
	"run_after_catch" smallint NOT NULL,
	"run_after_catch_potential" smallint NOT NULL,
	"pass_blocking" smallint NOT NULL,
	"pass_blocking_potential" smallint NOT NULL,
	"run_blocking" smallint NOT NULL,
	"run_blocking_potential" smallint NOT NULL,
	"block_shedding" smallint NOT NULL,
	"block_shedding_potential" smallint NOT NULL,
	"tackling" smallint NOT NULL,
	"tackling_potential" smallint NOT NULL,
	"man_coverage" smallint NOT NULL,
	"man_coverage_potential" smallint NOT NULL,
	"zone_coverage" smallint NOT NULL,
	"zone_coverage_potential" smallint NOT NULL,
	"pass_rushing" smallint NOT NULL,
	"pass_rushing_potential" smallint NOT NULL,
	"run_defense" smallint NOT NULL,
	"run_defense_potential" smallint NOT NULL,
	"kicking_power" smallint NOT NULL,
	"kicking_power_potential" smallint NOT NULL,
	"kicking_accuracy" smallint NOT NULL,
	"kicking_accuracy_potential" smallint NOT NULL,
	"punting_power" smallint NOT NULL,
	"punting_power_potential" smallint NOT NULL,
	"punting_accuracy" smallint NOT NULL,
	"punting_accuracy_potential" smallint NOT NULL,
	"snap_accuracy" smallint NOT NULL,
	"snap_accuracy_potential" smallint NOT NULL,
	"football_iq" smallint NOT NULL,
	"football_iq_potential" smallint NOT NULL,
	"decision_making" smallint NOT NULL,
	"decision_making_potential" smallint NOT NULL,
	"anticipation" smallint NOT NULL,
	"anticipation_potential" smallint NOT NULL,
	"composure" smallint NOT NULL,
	"composure_potential" smallint NOT NULL,
	"clutch" smallint NOT NULL,
	"clutch_potential" smallint NOT NULL,
	"consistency" smallint NOT NULL,
	"consistency_potential" smallint NOT NULL,
	"work_ethic" smallint NOT NULL,
	"work_ethic_potential" smallint NOT NULL,
	"coachability" smallint NOT NULL,
	"coachability_potential" smallint NOT NULL,
	"leadership" smallint NOT NULL,
	"leadership_potential" smallint NOT NULL,
	"greed" smallint NOT NULL,
	"greed_potential" smallint NOT NULL,
	"loyalty" smallint NOT NULL,
	"loyalty_potential" smallint NOT NULL,
	"ambition" smallint NOT NULL,
	"ambition_potential" smallint NOT NULL,
	"vanity" smallint NOT NULL,
	"vanity_potential" smallint NOT NULL,
	"scheme_attachment" smallint NOT NULL,
	"scheme_attachment_potential" smallint NOT NULL,
	"media_sensitivity" smallint NOT NULL,
	"media_sensitivity_potential" smallint NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "draft_prospect_attributes_speed_range" CHECK (speed BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_speed_potential_range" CHECK (speed_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_acceleration_range" CHECK (acceleration BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_acceleration_potential_range" CHECK (acceleration_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_agility_range" CHECK (agility BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_agility_potential_range" CHECK (agility_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_strength_range" CHECK (strength BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_strength_potential_range" CHECK (strength_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_jumping_range" CHECK (jumping BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_jumping_potential_range" CHECK (jumping_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_stamina_range" CHECK (stamina BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_stamina_potential_range" CHECK (stamina_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_durability_range" CHECK (durability BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_durability_potential_range" CHECK (durability_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_arm_strength_range" CHECK (arm_strength BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_arm_strength_potential_range" CHECK (arm_strength_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_accuracy_short_range" CHECK (accuracy_short BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_accuracy_short_potential_range" CHECK (accuracy_short_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_accuracy_medium_range" CHECK (accuracy_medium BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_accuracy_medium_potential_range" CHECK (accuracy_medium_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_accuracy_deep_range" CHECK (accuracy_deep BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_accuracy_deep_potential_range" CHECK (accuracy_deep_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_accuracy_on_the_run_range" CHECK (accuracy_on_the_run BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_accuracy_on_the_run_potential_range" CHECK (accuracy_on_the_run_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_touch_range" CHECK (touch BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_touch_potential_range" CHECK (touch_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_release_range" CHECK (release BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_release_potential_range" CHECK (release_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_ball_carrying_range" CHECK (ball_carrying BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_ball_carrying_potential_range" CHECK (ball_carrying_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_elusiveness_range" CHECK (elusiveness BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_elusiveness_potential_range" CHECK (elusiveness_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_route_running_range" CHECK (route_running BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_route_running_potential_range" CHECK (route_running_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_catching_range" CHECK (catching BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_catching_potential_range" CHECK (catching_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_contested_catching_range" CHECK (contested_catching BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_contested_catching_potential_range" CHECK (contested_catching_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_run_after_catch_range" CHECK (run_after_catch BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_run_after_catch_potential_range" CHECK (run_after_catch_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_pass_blocking_range" CHECK (pass_blocking BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_pass_blocking_potential_range" CHECK (pass_blocking_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_run_blocking_range" CHECK (run_blocking BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_run_blocking_potential_range" CHECK (run_blocking_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_block_shedding_range" CHECK (block_shedding BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_block_shedding_potential_range" CHECK (block_shedding_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_tackling_range" CHECK (tackling BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_tackling_potential_range" CHECK (tackling_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_man_coverage_range" CHECK (man_coverage BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_man_coverage_potential_range" CHECK (man_coverage_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_zone_coverage_range" CHECK (zone_coverage BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_zone_coverage_potential_range" CHECK (zone_coverage_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_pass_rushing_range" CHECK (pass_rushing BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_pass_rushing_potential_range" CHECK (pass_rushing_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_run_defense_range" CHECK (run_defense BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_run_defense_potential_range" CHECK (run_defense_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_kicking_power_range" CHECK (kicking_power BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_kicking_power_potential_range" CHECK (kicking_power_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_kicking_accuracy_range" CHECK (kicking_accuracy BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_kicking_accuracy_potential_range" CHECK (kicking_accuracy_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_punting_power_range" CHECK (punting_power BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_punting_power_potential_range" CHECK (punting_power_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_punting_accuracy_range" CHECK (punting_accuracy BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_punting_accuracy_potential_range" CHECK (punting_accuracy_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_snap_accuracy_range" CHECK (snap_accuracy BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_snap_accuracy_potential_range" CHECK (snap_accuracy_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_football_iq_range" CHECK (football_iq BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_football_iq_potential_range" CHECK (football_iq_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_decision_making_range" CHECK (decision_making BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_decision_making_potential_range" CHECK (decision_making_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_anticipation_range" CHECK (anticipation BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_anticipation_potential_range" CHECK (anticipation_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_composure_range" CHECK (composure BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_composure_potential_range" CHECK (composure_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_clutch_range" CHECK (clutch BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_clutch_potential_range" CHECK (clutch_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_consistency_range" CHECK (consistency BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_consistency_potential_range" CHECK (consistency_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_work_ethic_range" CHECK (work_ethic BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_work_ethic_potential_range" CHECK (work_ethic_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_coachability_range" CHECK (coachability BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_coachability_potential_range" CHECK (coachability_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_leadership_range" CHECK (leadership BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_leadership_potential_range" CHECK (leadership_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_greed_range" CHECK (greed BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_greed_potential_range" CHECK (greed_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_loyalty_range" CHECK (loyalty BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_loyalty_potential_range" CHECK (loyalty_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_ambition_range" CHECK (ambition BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_ambition_potential_range" CHECK (ambition_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_vanity_range" CHECK (vanity BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_vanity_potential_range" CHECK (vanity_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_scheme_attachment_range" CHECK (scheme_attachment BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_scheme_attachment_potential_range" CHECK (scheme_attachment_potential BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_media_sensitivity_range" CHECK (media_sensitivity BETWEEN 0 AND 100),
	CONSTRAINT "draft_prospect_attributes_media_sensitivity_potential_range" CHECK (media_sensitivity_potential BETWEEN 0 AND 100)
);
--> statement-breakpoint
CREATE TABLE "player_attributes" (
	"player_id" uuid PRIMARY KEY NOT NULL,
	"speed" smallint NOT NULL,
	"speed_potential" smallint NOT NULL,
	"acceleration" smallint NOT NULL,
	"acceleration_potential" smallint NOT NULL,
	"agility" smallint NOT NULL,
	"agility_potential" smallint NOT NULL,
	"strength" smallint NOT NULL,
	"strength_potential" smallint NOT NULL,
	"jumping" smallint NOT NULL,
	"jumping_potential" smallint NOT NULL,
	"stamina" smallint NOT NULL,
	"stamina_potential" smallint NOT NULL,
	"durability" smallint NOT NULL,
	"durability_potential" smallint NOT NULL,
	"arm_strength" smallint NOT NULL,
	"arm_strength_potential" smallint NOT NULL,
	"accuracy_short" smallint NOT NULL,
	"accuracy_short_potential" smallint NOT NULL,
	"accuracy_medium" smallint NOT NULL,
	"accuracy_medium_potential" smallint NOT NULL,
	"accuracy_deep" smallint NOT NULL,
	"accuracy_deep_potential" smallint NOT NULL,
	"accuracy_on_the_run" smallint NOT NULL,
	"accuracy_on_the_run_potential" smallint NOT NULL,
	"touch" smallint NOT NULL,
	"touch_potential" smallint NOT NULL,
	"release" smallint NOT NULL,
	"release_potential" smallint NOT NULL,
	"ball_carrying" smallint NOT NULL,
	"ball_carrying_potential" smallint NOT NULL,
	"elusiveness" smallint NOT NULL,
	"elusiveness_potential" smallint NOT NULL,
	"route_running" smallint NOT NULL,
	"route_running_potential" smallint NOT NULL,
	"catching" smallint NOT NULL,
	"catching_potential" smallint NOT NULL,
	"contested_catching" smallint NOT NULL,
	"contested_catching_potential" smallint NOT NULL,
	"run_after_catch" smallint NOT NULL,
	"run_after_catch_potential" smallint NOT NULL,
	"pass_blocking" smallint NOT NULL,
	"pass_blocking_potential" smallint NOT NULL,
	"run_blocking" smallint NOT NULL,
	"run_blocking_potential" smallint NOT NULL,
	"block_shedding" smallint NOT NULL,
	"block_shedding_potential" smallint NOT NULL,
	"tackling" smallint NOT NULL,
	"tackling_potential" smallint NOT NULL,
	"man_coverage" smallint NOT NULL,
	"man_coverage_potential" smallint NOT NULL,
	"zone_coverage" smallint NOT NULL,
	"zone_coverage_potential" smallint NOT NULL,
	"pass_rushing" smallint NOT NULL,
	"pass_rushing_potential" smallint NOT NULL,
	"run_defense" smallint NOT NULL,
	"run_defense_potential" smallint NOT NULL,
	"kicking_power" smallint NOT NULL,
	"kicking_power_potential" smallint NOT NULL,
	"kicking_accuracy" smallint NOT NULL,
	"kicking_accuracy_potential" smallint NOT NULL,
	"punting_power" smallint NOT NULL,
	"punting_power_potential" smallint NOT NULL,
	"punting_accuracy" smallint NOT NULL,
	"punting_accuracy_potential" smallint NOT NULL,
	"snap_accuracy" smallint NOT NULL,
	"snap_accuracy_potential" smallint NOT NULL,
	"football_iq" smallint NOT NULL,
	"football_iq_potential" smallint NOT NULL,
	"decision_making" smallint NOT NULL,
	"decision_making_potential" smallint NOT NULL,
	"anticipation" smallint NOT NULL,
	"anticipation_potential" smallint NOT NULL,
	"composure" smallint NOT NULL,
	"composure_potential" smallint NOT NULL,
	"clutch" smallint NOT NULL,
	"clutch_potential" smallint NOT NULL,
	"consistency" smallint NOT NULL,
	"consistency_potential" smallint NOT NULL,
	"work_ethic" smallint NOT NULL,
	"work_ethic_potential" smallint NOT NULL,
	"coachability" smallint NOT NULL,
	"coachability_potential" smallint NOT NULL,
	"leadership" smallint NOT NULL,
	"leadership_potential" smallint NOT NULL,
	"greed" smallint NOT NULL,
	"greed_potential" smallint NOT NULL,
	"loyalty" smallint NOT NULL,
	"loyalty_potential" smallint NOT NULL,
	"ambition" smallint NOT NULL,
	"ambition_potential" smallint NOT NULL,
	"vanity" smallint NOT NULL,
	"vanity_potential" smallint NOT NULL,
	"scheme_attachment" smallint NOT NULL,
	"scheme_attachment_potential" smallint NOT NULL,
	"media_sensitivity" smallint NOT NULL,
	"media_sensitivity_potential" smallint NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "player_attributes_speed_range" CHECK (speed BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_speed_potential_range" CHECK (speed_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_acceleration_range" CHECK (acceleration BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_acceleration_potential_range" CHECK (acceleration_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_agility_range" CHECK (agility BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_agility_potential_range" CHECK (agility_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_strength_range" CHECK (strength BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_strength_potential_range" CHECK (strength_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_jumping_range" CHECK (jumping BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_jumping_potential_range" CHECK (jumping_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_stamina_range" CHECK (stamina BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_stamina_potential_range" CHECK (stamina_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_durability_range" CHECK (durability BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_durability_potential_range" CHECK (durability_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_arm_strength_range" CHECK (arm_strength BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_arm_strength_potential_range" CHECK (arm_strength_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_accuracy_short_range" CHECK (accuracy_short BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_accuracy_short_potential_range" CHECK (accuracy_short_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_accuracy_medium_range" CHECK (accuracy_medium BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_accuracy_medium_potential_range" CHECK (accuracy_medium_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_accuracy_deep_range" CHECK (accuracy_deep BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_accuracy_deep_potential_range" CHECK (accuracy_deep_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_accuracy_on_the_run_range" CHECK (accuracy_on_the_run BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_accuracy_on_the_run_potential_range" CHECK (accuracy_on_the_run_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_touch_range" CHECK (touch BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_touch_potential_range" CHECK (touch_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_release_range" CHECK (release BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_release_potential_range" CHECK (release_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_ball_carrying_range" CHECK (ball_carrying BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_ball_carrying_potential_range" CHECK (ball_carrying_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_elusiveness_range" CHECK (elusiveness BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_elusiveness_potential_range" CHECK (elusiveness_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_route_running_range" CHECK (route_running BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_route_running_potential_range" CHECK (route_running_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_catching_range" CHECK (catching BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_catching_potential_range" CHECK (catching_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_contested_catching_range" CHECK (contested_catching BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_contested_catching_potential_range" CHECK (contested_catching_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_run_after_catch_range" CHECK (run_after_catch BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_run_after_catch_potential_range" CHECK (run_after_catch_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_pass_blocking_range" CHECK (pass_blocking BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_pass_blocking_potential_range" CHECK (pass_blocking_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_run_blocking_range" CHECK (run_blocking BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_run_blocking_potential_range" CHECK (run_blocking_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_block_shedding_range" CHECK (block_shedding BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_block_shedding_potential_range" CHECK (block_shedding_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_tackling_range" CHECK (tackling BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_tackling_potential_range" CHECK (tackling_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_man_coverage_range" CHECK (man_coverage BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_man_coverage_potential_range" CHECK (man_coverage_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_zone_coverage_range" CHECK (zone_coverage BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_zone_coverage_potential_range" CHECK (zone_coverage_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_pass_rushing_range" CHECK (pass_rushing BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_pass_rushing_potential_range" CHECK (pass_rushing_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_run_defense_range" CHECK (run_defense BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_run_defense_potential_range" CHECK (run_defense_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_kicking_power_range" CHECK (kicking_power BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_kicking_power_potential_range" CHECK (kicking_power_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_kicking_accuracy_range" CHECK (kicking_accuracy BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_kicking_accuracy_potential_range" CHECK (kicking_accuracy_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_punting_power_range" CHECK (punting_power BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_punting_power_potential_range" CHECK (punting_power_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_punting_accuracy_range" CHECK (punting_accuracy BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_punting_accuracy_potential_range" CHECK (punting_accuracy_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_snap_accuracy_range" CHECK (snap_accuracy BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_snap_accuracy_potential_range" CHECK (snap_accuracy_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_football_iq_range" CHECK (football_iq BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_football_iq_potential_range" CHECK (football_iq_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_decision_making_range" CHECK (decision_making BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_decision_making_potential_range" CHECK (decision_making_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_anticipation_range" CHECK (anticipation BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_anticipation_potential_range" CHECK (anticipation_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_composure_range" CHECK (composure BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_composure_potential_range" CHECK (composure_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_clutch_range" CHECK (clutch BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_clutch_potential_range" CHECK (clutch_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_consistency_range" CHECK (consistency BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_consistency_potential_range" CHECK (consistency_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_work_ethic_range" CHECK (work_ethic BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_work_ethic_potential_range" CHECK (work_ethic_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_coachability_range" CHECK (coachability BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_coachability_potential_range" CHECK (coachability_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_leadership_range" CHECK (leadership BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_leadership_potential_range" CHECK (leadership_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_greed_range" CHECK (greed BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_greed_potential_range" CHECK (greed_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_loyalty_range" CHECK (loyalty BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_loyalty_potential_range" CHECK (loyalty_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_ambition_range" CHECK (ambition BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_ambition_potential_range" CHECK (ambition_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_vanity_range" CHECK (vanity BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_vanity_potential_range" CHECK (vanity_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_scheme_attachment_range" CHECK (scheme_attachment BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_scheme_attachment_potential_range" CHECK (scheme_attachment_potential BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_media_sensitivity_range" CHECK (media_sensitivity BETWEEN 0 AND 100),
	CONSTRAINT "player_attributes_media_sensitivity_potential_range" CHECK (media_sensitivity_potential BETWEEN 0 AND 100)
);
--> statement-breakpoint
ALTER TABLE "draft_prospects" ADD COLUMN "height_inches" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "draft_prospects" ADD COLUMN "weight_pounds" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "draft_prospects" ADD COLUMN "college" text;--> statement-breakpoint
ALTER TABLE "draft_prospects" ADD COLUMN "birth_date" date NOT NULL;--> statement-breakpoint
ALTER TABLE "players" ADD COLUMN "height_inches" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "players" ADD COLUMN "weight_pounds" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "players" ADD COLUMN "college" text;--> statement-breakpoint
ALTER TABLE "players" ADD COLUMN "birth_date" date NOT NULL;--> statement-breakpoint
ALTER TABLE "draft_prospect_attributes" ADD CONSTRAINT "draft_prospect_attributes_draft_prospect_id_draft_prospects_id_fk" FOREIGN KEY ("draft_prospect_id") REFERENCES "public"."draft_prospects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_attributes" ADD CONSTRAINT "player_attributes_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE cascade ON UPDATE no action;