UPDATE "franchises" SET "backstory" = 'Born from the neon glow and high-stakes spirit of the Biggest Little City, the Aces play every down like a winning hand. Their silver-and-black swagger reflects Reno''s gritty reinvention from gaming town to mountain-sports hub.' WHERE "abbreviation" = 'RNO';--> statement-breakpoint
UPDATE "franchises" SET "backstory" = 'Forged in Portland''s shipyard heritage, the Riveters honor the workers who built the West. Rain or shine, they bring a blue-collar intensity wrapped in the city''s famously independent streak.' WHERE "abbreviation" = 'PDX';--> statement-breakpoint
UPDATE "franchises" SET "backstory" = 'California''s capital city stakes its claim with the Republic — a franchise built on civic pride and the golden promise of the Central Valley. Deep crimson and gold fly over a fanbase hungry to prove Sacramento belongs on any stage.' WHERE "abbreviation" = 'SAC';--> statement-breakpoint
UPDATE "franchises" SET "backstory" = 'With a naval heritage stretching back generations, the Admirals command San Diego''s waterfront with precision and pride. Sun-soaked fans pack the harbor-side stadium to watch a disciplined squad that mirrors the city''s military tradition.' WHERE "abbreviation" = 'SDG';--> statement-breakpoint
UPDATE "franchises" SET "backstory" = 'Nestled against the Wasatch Range, the Pioneers carry the trailblazing spirit of Utah''s founders onto the gridiron. Their purple-and-white banner symbolizes the rugged determination that carved a home out of the mountain frontier.' WHERE "abbreviation" = 'SLC';--> statement-breakpoint
UPDATE "franchises" SET "backstory" = 'Idaho''s proudest export isn''t just potatoes — it''s the Spuds, a scrappy franchise that wears its agricultural roots with tongue-in-cheek swagger. Orange-and-teal faithful pack the stands in Boise, daring anyone to underestimate a team named after a tuber.' WHERE "abbreviation" = 'BOI';--> statement-breakpoint
UPDATE "franchises" SET "backstory" = 'Erupting from the volcanic heart of the Pacific, the Lava bring island fire to the mainland. Honolulu''s entry plays with an explosive, fast-paced style as fierce as the molten flows of Kīlauea.' WHERE "abbreviation" = 'HNL';--> statement-breakpoint
UPDATE "franchises" SET "backstory" = 'Speeding across the high desert, the Roadrunners capture Albuquerque''s wide-open frontier energy. Teal and gold flash under the Sandia Mountain sunset as this franchise races to outrun every expectation.' WHERE "abbreviation" = 'ABQ';--> statement-breakpoint
UPDATE "teams" t SET "backstory" = f."backstory" FROM "franchises" f WHERE t."franchise_id" = f."id" AND (t."backstory" IS NULL OR t."backstory" = '');
