spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms
