server:
  port: 3000

spring:
  application:
    name: zoneblitz
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID:}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
  datasource:
    url: jdbc:postgresql://localhost:5432/zoneblitz
    username: zoneblitz
    password: zoneblitz
  jooq:
    sql-dialect: POSTGRES
  flyway:
    locations: classpath:db/migration
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
