/**
 * Seed data for NCAA Division I football programs (FBS and FCS).
 *
 * Used as the domain reference for coach alma maters. School names, cities,
 * nicknames, and conference affiliations are public facts. Logos, trademarks,
 * and proprietary identity are intentionally not stored here.
 *
 * Conference alignment is a snapshot of the 2024-2025 season; teams that have
 * since reclassified may appear under their newer subdivision.
 */
export interface DefaultCollege {
  name: string;
  shortName: string;
  nickname: string;
  city: string;
  state: string;
  conference: string;
  subdivision: "FBS" | "FCS";
}

export const DEFAULT_COLLEGES: DefaultCollege[] = [
  // === FBS ===
  {
    name: "University of Akron",
    shortName: "Akron",
    nickname: "Zips",
    city: "Akron",
    state: "OH",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "University of Alabama",
    shortName: "Alabama",
    nickname: "Crimson Tide",
    city: "Tuscaloosa",
    state: "AL",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "University of Alabama at Birmingham",
    shortName: "UAB",
    nickname: "Blazers",
    city: "Birmingham",
    state: "AL",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "Appalachian State University",
    shortName: "Appalachian State",
    nickname: "Mountaineers",
    city: "Boone",
    state: "NC",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "University of Arizona",
    shortName: "Arizona",
    nickname: "Wildcats",
    city: "Tucson",
    state: "AZ",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Arizona State University",
    shortName: "Arizona State",
    nickname: "Sun Devils",
    city: "Tempe",
    state: "AZ",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "University of Arkansas",
    shortName: "Arkansas",
    nickname: "Razorbacks",
    city: "Fayetteville",
    state: "AR",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Arkansas State University",
    shortName: "Arkansas State",
    nickname: "Red Wolves",
    city: "Jonesboro",
    state: "AR",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "United States Air Force Academy",
    shortName: "Air Force",
    nickname: "Falcons",
    city: "USAF Academy",
    state: "CO",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "United States Military Academy",
    shortName: "Army",
    nickname: "Black Knights",
    city: "West Point",
    state: "NY",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "Auburn University",
    shortName: "Auburn",
    nickname: "Tigers",
    city: "Auburn",
    state: "AL",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Baylor University",
    shortName: "Baylor",
    nickname: "Bears",
    city: "Waco",
    state: "TX",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Boise State University",
    shortName: "Boise State",
    nickname: "Broncos",
    city: "Boise",
    state: "ID",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "Boston College",
    shortName: "Boston College",
    nickname: "Eagles",
    city: "Chestnut Hill",
    state: "MA",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Bowling Green State University",
    shortName: "Bowling Green",
    nickname: "Falcons",
    city: "Bowling Green",
    state: "OH",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "Brigham Young University",
    shortName: "BYU",
    nickname: "Cougars",
    city: "Provo",
    state: "UT",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "University at Buffalo",
    shortName: "Buffalo",
    nickname: "Bulls",
    city: "Buffalo",
    state: "NY",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "University of California, Berkeley",
    shortName: "California",
    nickname: "Golden Bears",
    city: "Berkeley",
    state: "CA",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "University of California, Los Angeles",
    shortName: "UCLA",
    nickname: "Bruins",
    city: "Los Angeles",
    state: "CA",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Central Michigan University",
    shortName: "Central Michigan",
    nickname: "Chippewas",
    city: "Mount Pleasant",
    state: "MI",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "University of Central Florida",
    shortName: "UCF",
    nickname: "Knights",
    city: "Orlando",
    state: "FL",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "University of Charlotte",
    shortName: "Charlotte",
    nickname: "49ers",
    city: "Charlotte",
    state: "NC",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "University of Cincinnati",
    shortName: "Cincinnati",
    nickname: "Bearcats",
    city: "Cincinnati",
    state: "OH",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Clemson University",
    shortName: "Clemson",
    nickname: "Tigers",
    city: "Clemson",
    state: "SC",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Coastal Carolina University",
    shortName: "Coastal Carolina",
    nickname: "Chanticleers",
    city: "Conway",
    state: "SC",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "University of Colorado Boulder",
    shortName: "Colorado",
    nickname: "Buffaloes",
    city: "Boulder",
    state: "CO",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Colorado State University",
    shortName: "Colorado State",
    nickname: "Rams",
    city: "Fort Collins",
    state: "CO",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "University of Connecticut",
    shortName: "UConn",
    nickname: "Huskies",
    city: "Storrs",
    state: "CT",
    conference: "Independent",
    subdivision: "FBS",
  },
  {
    name: "University of Delaware",
    shortName: "Delaware",
    nickname: "Fightin' Blue Hens",
    city: "Newark",
    state: "DE",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "Duke University",
    shortName: "Duke",
    nickname: "Blue Devils",
    city: "Durham",
    state: "NC",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "East Carolina University",
    shortName: "East Carolina",
    nickname: "Pirates",
    city: "Greenville",
    state: "NC",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "Eastern Michigan University",
    shortName: "Eastern Michigan",
    nickname: "Eagles",
    city: "Ypsilanti",
    state: "MI",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "Florida Atlantic University",
    shortName: "Florida Atlantic",
    nickname: "Owls",
    city: "Boca Raton",
    state: "FL",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "Florida International University",
    shortName: "FIU",
    nickname: "Panthers",
    city: "Miami",
    state: "FL",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "Florida State University",
    shortName: "Florida State",
    nickname: "Seminoles",
    city: "Tallahassee",
    state: "FL",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "University of Florida",
    shortName: "Florida",
    nickname: "Gators",
    city: "Gainesville",
    state: "FL",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "California State University, Fresno",
    shortName: "Fresno State",
    nickname: "Bulldogs",
    city: "Fresno",
    state: "CA",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "University of Georgia",
    shortName: "Georgia",
    nickname: "Bulldogs",
    city: "Athens",
    state: "GA",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Georgia Institute of Technology",
    shortName: "Georgia Tech",
    nickname: "Yellow Jackets",
    city: "Atlanta",
    state: "GA",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Georgia Southern University",
    shortName: "Georgia Southern",
    nickname: "Eagles",
    city: "Statesboro",
    state: "GA",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "Georgia State University",
    shortName: "Georgia State",
    nickname: "Panthers",
    city: "Atlanta",
    state: "GA",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "University of Hawaiʻi at Mānoa",
    shortName: "Hawaiʻi",
    nickname: "Rainbow Warriors",
    city: "Honolulu",
    state: "HI",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "University of Houston",
    shortName: "Houston",
    nickname: "Cougars",
    city: "Houston",
    state: "TX",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "University of Illinois Urbana-Champaign",
    shortName: "Illinois",
    nickname: "Fighting Illini",
    city: "Champaign",
    state: "IL",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Indiana University Bloomington",
    shortName: "Indiana",
    nickname: "Hoosiers",
    city: "Bloomington",
    state: "IN",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "University of Iowa",
    shortName: "Iowa",
    nickname: "Hawkeyes",
    city: "Iowa City",
    state: "IA",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Iowa State University",
    shortName: "Iowa State",
    nickname: "Cyclones",
    city: "Ames",
    state: "IA",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Jacksonville State University",
    shortName: "Jacksonville State",
    nickname: "Gamecocks",
    city: "Jacksonville",
    state: "AL",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "James Madison University",
    shortName: "James Madison",
    nickname: "Dukes",
    city: "Harrisonburg",
    state: "VA",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "University of Kansas",
    shortName: "Kansas",
    nickname: "Jayhawks",
    city: "Lawrence",
    state: "KS",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Kansas State University",
    shortName: "Kansas State",
    nickname: "Wildcats",
    city: "Manhattan",
    state: "KS",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Kennesaw State University",
    shortName: "Kennesaw State",
    nickname: "Owls",
    city: "Kennesaw",
    state: "GA",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "Kent State University",
    shortName: "Kent State",
    nickname: "Golden Flashes",
    city: "Kent",
    state: "OH",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "University of Kentucky",
    shortName: "Kentucky",
    nickname: "Wildcats",
    city: "Lexington",
    state: "KY",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Liberty University",
    shortName: "Liberty",
    nickname: "Flames",
    city: "Lynchburg",
    state: "VA",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "University of Louisiana at Lafayette",
    shortName: "Louisiana",
    nickname: "Ragin' Cajuns",
    city: "Lafayette",
    state: "LA",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "University of Louisiana at Monroe",
    shortName: "ULM",
    nickname: "Warhawks",
    city: "Monroe",
    state: "LA",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "Louisiana State University",
    shortName: "LSU",
    nickname: "Tigers",
    city: "Baton Rouge",
    state: "LA",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Louisiana Tech University",
    shortName: "Louisiana Tech",
    nickname: "Bulldogs",
    city: "Ruston",
    state: "LA",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "University of Louisville",
    shortName: "Louisville",
    nickname: "Cardinals",
    city: "Louisville",
    state: "KY",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Marshall University",
    shortName: "Marshall",
    nickname: "Thundering Herd",
    city: "Huntington",
    state: "WV",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "University of Maryland",
    shortName: "Maryland",
    nickname: "Terrapins",
    city: "College Park",
    state: "MD",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "University of Massachusetts Amherst",
    shortName: "UMass",
    nickname: "Minutemen",
    city: "Amherst",
    state: "MA",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "University of Memphis",
    shortName: "Memphis",
    nickname: "Tigers",
    city: "Memphis",
    state: "TN",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "University of Miami",
    shortName: "Miami (FL)",
    nickname: "Hurricanes",
    city: "Coral Gables",
    state: "FL",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Miami University",
    shortName: "Miami (OH)",
    nickname: "RedHawks",
    city: "Oxford",
    state: "OH",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "University of Michigan",
    shortName: "Michigan",
    nickname: "Wolverines",
    city: "Ann Arbor",
    state: "MI",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Michigan State University",
    shortName: "Michigan State",
    nickname: "Spartans",
    city: "East Lansing",
    state: "MI",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Middle Tennessee State University",
    shortName: "Middle Tennessee",
    nickname: "Blue Raiders",
    city: "Murfreesboro",
    state: "TN",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "University of Minnesota",
    shortName: "Minnesota",
    nickname: "Golden Gophers",
    city: "Minneapolis",
    state: "MN",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Mississippi State University",
    shortName: "Mississippi State",
    nickname: "Bulldogs",
    city: "Starkville",
    state: "MS",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "University of Mississippi",
    shortName: "Ole Miss",
    nickname: "Rebels",
    city: "Oxford",
    state: "MS",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "University of Missouri",
    shortName: "Missouri",
    nickname: "Tigers",
    city: "Columbia",
    state: "MO",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Missouri State University",
    shortName: "Missouri State",
    nickname: "Bears",
    city: "Springfield",
    state: "MO",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "United States Naval Academy",
    shortName: "Navy",
    nickname: "Midshipmen",
    city: "Annapolis",
    state: "MD",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "University of Nebraska–Lincoln",
    shortName: "Nebraska",
    nickname: "Cornhuskers",
    city: "Lincoln",
    state: "NE",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "University of Nevada, Reno",
    shortName: "Nevada",
    nickname: "Wolf Pack",
    city: "Reno",
    state: "NV",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "University of Nevada, Las Vegas",
    shortName: "UNLV",
    nickname: "Rebels",
    city: "Las Vegas",
    state: "NV",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "University of New Mexico",
    shortName: "New Mexico",
    nickname: "Lobos",
    city: "Albuquerque",
    state: "NM",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "New Mexico State University",
    shortName: "New Mexico State",
    nickname: "Aggies",
    city: "Las Cruces",
    state: "NM",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "University of North Carolina at Chapel Hill",
    shortName: "North Carolina",
    nickname: "Tar Heels",
    city: "Chapel Hill",
    state: "NC",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "North Carolina State University",
    shortName: "NC State",
    nickname: "Wolfpack",
    city: "Raleigh",
    state: "NC",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "University of North Texas",
    shortName: "North Texas",
    nickname: "Mean Green",
    city: "Denton",
    state: "TX",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "Northern Illinois University",
    shortName: "Northern Illinois",
    nickname: "Huskies",
    city: "DeKalb",
    state: "IL",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "Northwestern University",
    shortName: "Northwestern",
    nickname: "Wildcats",
    city: "Evanston",
    state: "IL",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "University of Notre Dame",
    shortName: "Notre Dame",
    nickname: "Fighting Irish",
    city: "South Bend",
    state: "IN",
    conference: "Independent",
    subdivision: "FBS",
  },
  {
    name: "Ohio University",
    shortName: "Ohio",
    nickname: "Bobcats",
    city: "Athens",
    state: "OH",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "Ohio State University",
    shortName: "Ohio State",
    nickname: "Buckeyes",
    city: "Columbus",
    state: "OH",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "University of Oklahoma",
    shortName: "Oklahoma",
    nickname: "Sooners",
    city: "Norman",
    state: "OK",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Oklahoma State University",
    shortName: "Oklahoma State",
    nickname: "Cowboys",
    city: "Stillwater",
    state: "OK",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Old Dominion University",
    shortName: "Old Dominion",
    nickname: "Monarchs",
    city: "Norfolk",
    state: "VA",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "University of Oregon",
    shortName: "Oregon",
    nickname: "Ducks",
    city: "Eugene",
    state: "OR",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Oregon State University",
    shortName: "Oregon State",
    nickname: "Beavers",
    city: "Corvallis",
    state: "OR",
    conference: "Pac-12",
    subdivision: "FBS",
  },
  {
    name: "Pennsylvania State University",
    shortName: "Penn State",
    nickname: "Nittany Lions",
    city: "University Park",
    state: "PA",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "University of Pittsburgh",
    shortName: "Pittsburgh",
    nickname: "Panthers",
    city: "Pittsburgh",
    state: "PA",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Purdue University",
    shortName: "Purdue",
    nickname: "Boilermakers",
    city: "West Lafayette",
    state: "IN",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Rice University",
    shortName: "Rice",
    nickname: "Owls",
    city: "Houston",
    state: "TX",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "Rutgers University",
    shortName: "Rutgers",
    nickname: "Scarlet Knights",
    city: "Piscataway",
    state: "NJ",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "California State University, Sacramento",
    shortName: "Sacramento State",
    nickname: "Hornets",
    city: "Sacramento",
    state: "CA",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "Sam Houston State University",
    shortName: "Sam Houston",
    nickname: "Bearkats",
    city: "Huntsville",
    state: "TX",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "San Diego State University",
    shortName: "San Diego State",
    nickname: "Aztecs",
    city: "San Diego",
    state: "CA",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "San Jose State University",
    shortName: "San Jose State",
    nickname: "Spartans",
    city: "San Jose",
    state: "CA",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "Southern Methodist University",
    shortName: "SMU",
    nickname: "Mustangs",
    city: "University Park",
    state: "TX",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "University of South Alabama",
    shortName: "South Alabama",
    nickname: "Jaguars",
    city: "Mobile",
    state: "AL",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "University of South Carolina",
    shortName: "South Carolina",
    nickname: "Gamecocks",
    city: "Columbia",
    state: "SC",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "University of South Florida",
    shortName: "South Florida",
    nickname: "Bulls",
    city: "Tampa",
    state: "FL",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "University of Southern California",
    shortName: "USC",
    nickname: "Trojans",
    city: "Los Angeles",
    state: "CA",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "University of Southern Mississippi",
    shortName: "Southern Miss",
    nickname: "Golden Eagles",
    city: "Hattiesburg",
    state: "MS",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "Stanford University",
    shortName: "Stanford",
    nickname: "Cardinal",
    city: "Stanford",
    state: "CA",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Syracuse University",
    shortName: "Syracuse",
    nickname: "Orange",
    city: "Syracuse",
    state: "NY",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Temple University",
    shortName: "Temple",
    nickname: "Owls",
    city: "Philadelphia",
    state: "PA",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "University of Tennessee",
    shortName: "Tennessee",
    nickname: "Volunteers",
    city: "Knoxville",
    state: "TN",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Texas A&M University",
    shortName: "Texas A&M",
    nickname: "Aggies",
    city: "College Station",
    state: "TX",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "Texas Christian University",
    shortName: "TCU",
    nickname: "Horned Frogs",
    city: "Fort Worth",
    state: "TX",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "University of Texas at Austin",
    shortName: "Texas",
    nickname: "Longhorns",
    city: "Austin",
    state: "TX",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "University of Texas at El Paso",
    shortName: "UTEP",
    nickname: "Miners",
    city: "El Paso",
    state: "TX",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "University of Texas at San Antonio",
    shortName: "UTSA",
    nickname: "Roadrunners",
    city: "San Antonio",
    state: "TX",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "Texas State University",
    shortName: "Texas State",
    nickname: "Bobcats",
    city: "San Marcos",
    state: "TX",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "Texas Tech University",
    shortName: "Texas Tech",
    nickname: "Red Raiders",
    city: "Lubbock",
    state: "TX",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "University of Toledo",
    shortName: "Toledo",
    nickname: "Rockets",
    city: "Toledo",
    state: "OH",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "Troy University",
    shortName: "Troy",
    nickname: "Trojans",
    city: "Troy",
    state: "AL",
    conference: "Sun Belt",
    subdivision: "FBS",
  },
  {
    name: "Tulane University",
    shortName: "Tulane",
    nickname: "Green Wave",
    city: "New Orleans",
    state: "LA",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "University of Tulsa",
    shortName: "Tulsa",
    nickname: "Golden Hurricane",
    city: "Tulsa",
    state: "OK",
    conference: "American",
    subdivision: "FBS",
  },
  {
    name: "University of Utah",
    shortName: "Utah",
    nickname: "Utes",
    city: "Salt Lake City",
    state: "UT",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Utah State University",
    shortName: "Utah State",
    nickname: "Aggies",
    city: "Logan",
    state: "UT",
    conference: "Mountain West",
    subdivision: "FBS",
  },
  {
    name: "Vanderbilt University",
    shortName: "Vanderbilt",
    nickname: "Commodores",
    city: "Nashville",
    state: "TN",
    conference: "SEC",
    subdivision: "FBS",
  },
  {
    name: "University of Virginia",
    shortName: "Virginia",
    nickname: "Cavaliers",
    city: "Charlottesville",
    state: "VA",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Virginia Polytechnic Institute and State University",
    shortName: "Virginia Tech",
    nickname: "Hokies",
    city: "Blacksburg",
    state: "VA",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "Wake Forest University",
    shortName: "Wake Forest",
    nickname: "Demon Deacons",
    city: "Winston-Salem",
    state: "NC",
    conference: "ACC",
    subdivision: "FBS",
  },
  {
    name: "University of Washington",
    shortName: "Washington",
    nickname: "Huskies",
    city: "Seattle",
    state: "WA",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "Washington State University",
    shortName: "Washington State",
    nickname: "Cougars",
    city: "Pullman",
    state: "WA",
    conference: "Pac-12",
    subdivision: "FBS",
  },
  {
    name: "West Virginia University",
    shortName: "West Virginia",
    nickname: "Mountaineers",
    city: "Morgantown",
    state: "WV",
    conference: "Big 12",
    subdivision: "FBS",
  },
  {
    name: "Western Kentucky University",
    shortName: "Western Kentucky",
    nickname: "Hilltoppers",
    city: "Bowling Green",
    state: "KY",
    conference: "CUSA",
    subdivision: "FBS",
  },
  {
    name: "Western Michigan University",
    shortName: "Western Michigan",
    nickname: "Broncos",
    city: "Kalamazoo",
    state: "MI",
    conference: "MAC",
    subdivision: "FBS",
  },
  {
    name: "University of Wisconsin–Madison",
    shortName: "Wisconsin",
    nickname: "Badgers",
    city: "Madison",
    state: "WI",
    conference: "Big Ten",
    subdivision: "FBS",
  },
  {
    name: "University of Wyoming",
    shortName: "Wyoming",
    nickname: "Cowboys",
    city: "Laramie",
    state: "WY",
    conference: "Mountain West",
    subdivision: "FBS",
  },

  // === FCS ===
  {
    name: "Abilene Christian University",
    shortName: "Abilene Christian",
    nickname: "Wildcats",
    city: "Abilene",
    state: "TX",
    conference: "UAC",
    subdivision: "FCS",
  },
  {
    name: "Alabama A&M University",
    shortName: "Alabama A&M",
    nickname: "Bulldogs",
    city: "Normal",
    state: "AL",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Alabama State University",
    shortName: "Alabama State",
    nickname: "Hornets",
    city: "Montgomery",
    state: "AL",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "State University of New York at Albany",
    shortName: "Albany",
    nickname: "Great Danes",
    city: "Albany",
    state: "NY",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "Alcorn State University",
    shortName: "Alcorn State",
    nickname: "Braves",
    city: "Lorman",
    state: "MS",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "University of Arkansas at Pine Bluff",
    shortName: "Arkansas–Pine Bluff",
    nickname: "Golden Lions",
    city: "Pine Bluff",
    state: "AR",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Austin Peay State University",
    shortName: "Austin Peay",
    nickname: "Governors",
    city: "Clarksville",
    state: "TN",
    conference: "UAC",
    subdivision: "FCS",
  },
  {
    name: "Bethune–Cookman University",
    shortName: "Bethune–Cookman",
    nickname: "Wildcats",
    city: "Daytona Beach",
    state: "FL",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Brown University",
    shortName: "Brown",
    nickname: "Bears",
    city: "Providence",
    state: "RI",
    conference: "Ivy",
    subdivision: "FCS",
  },
  {
    name: "Bryant University",
    shortName: "Bryant",
    nickname: "Bulldogs",
    city: "Smithfield",
    state: "RI",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "Bucknell University",
    shortName: "Bucknell",
    nickname: "Bison",
    city: "Lewisburg",
    state: "PA",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Butler University",
    shortName: "Butler",
    nickname: "Bulldogs",
    city: "Indianapolis",
    state: "IN",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "California Polytechnic State University",
    shortName: "Cal Poly",
    nickname: "Mustangs",
    city: "San Luis Obispo",
    state: "CA",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "Campbell University",
    shortName: "Campbell",
    nickname: "Fighting Camels",
    city: "Buies Creek",
    state: "NC",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "University of Central Arkansas",
    shortName: "Central Arkansas",
    nickname: "Bears",
    city: "Conway",
    state: "AR",
    conference: "UAC",
    subdivision: "FCS",
  },
  {
    name: "Central Connecticut State University",
    shortName: "Central Connecticut",
    nickname: "Blue Devils",
    city: "New Britain",
    state: "CT",
    conference: "NEC",
    subdivision: "FCS",
  },
  {
    name: "Charleston Southern University",
    shortName: "Charleston Southern",
    nickname: "Buccaneers",
    city: "North Charleston",
    state: "SC",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "University of Tennessee at Chattanooga",
    shortName: "Chattanooga",
    nickname: "Mocs",
    city: "Chattanooga",
    state: "TN",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "The Citadel",
    shortName: "The Citadel",
    nickname: "Bulldogs",
    city: "Charleston",
    state: "SC",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "Colgate University",
    shortName: "Colgate",
    nickname: "Raiders",
    city: "Hamilton",
    state: "NY",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Columbia University",
    shortName: "Columbia",
    nickname: "Lions",
    city: "New York",
    state: "NY",
    conference: "Ivy",
    subdivision: "FCS",
  },
  {
    name: "Cornell University",
    shortName: "Cornell",
    nickname: "Big Red",
    city: "Ithaca",
    state: "NY",
    conference: "Ivy",
    subdivision: "FCS",
  },
  {
    name: "Dartmouth College",
    shortName: "Dartmouth",
    nickname: "Big Green",
    city: "Hanover",
    state: "NH",
    conference: "Ivy",
    subdivision: "FCS",
  },
  {
    name: "Davidson College",
    shortName: "Davidson",
    nickname: "Wildcats",
    city: "Davidson",
    state: "NC",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "University of Dayton",
    shortName: "Dayton",
    nickname: "Flyers",
    city: "Dayton",
    state: "OH",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "Delaware State University",
    shortName: "Delaware State",
    nickname: "Hornets",
    city: "Dover",
    state: "DE",
    conference: "MEAC",
    subdivision: "FCS",
  },
  {
    name: "Drake University",
    shortName: "Drake",
    nickname: "Bulldogs",
    city: "Des Moines",
    state: "IA",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "Duquesne University",
    shortName: "Duquesne",
    nickname: "Dukes",
    city: "Pittsburgh",
    state: "PA",
    conference: "NEC",
    subdivision: "FCS",
  },
  {
    name: "East Tennessee State University",
    shortName: "East Tennessee State",
    nickname: "Buccaneers",
    city: "Johnson City",
    state: "TN",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "East Texas A&M University",
    shortName: "East Texas A&M",
    nickname: "Lions",
    city: "Commerce",
    state: "TX",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Eastern Illinois University",
    shortName: "Eastern Illinois",
    nickname: "Panthers",
    city: "Charleston",
    state: "IL",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "Eastern Kentucky University",
    shortName: "Eastern Kentucky",
    nickname: "Colonels",
    city: "Richmond",
    state: "KY",
    conference: "UAC",
    subdivision: "FCS",
  },
  {
    name: "Eastern Washington University",
    shortName: "Eastern Washington",
    nickname: "Eagles",
    city: "Cheney",
    state: "WA",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "Elon University",
    shortName: "Elon",
    nickname: "Phoenix",
    city: "Elon",
    state: "NC",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "Florida A&M University",
    shortName: "Florida A&M",
    nickname: "Rattlers",
    city: "Tallahassee",
    state: "FL",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Fordham University",
    shortName: "Fordham",
    nickname: "Rams",
    city: "New York",
    state: "NY",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Furman University",
    shortName: "Furman",
    nickname: "Paladins",
    city: "Greenville",
    state: "SC",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "Gardner–Webb University",
    shortName: "Gardner–Webb",
    nickname: "Runnin' Bulldogs",
    city: "Boiling Springs",
    state: "NC",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "Georgetown University",
    shortName: "Georgetown",
    nickname: "Hoyas",
    city: "Washington",
    state: "DC",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Grambling State University",
    shortName: "Grambling State",
    nickname: "Tigers",
    city: "Grambling",
    state: "LA",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Hampton University",
    shortName: "Hampton",
    nickname: "Pirates",
    city: "Hampton",
    state: "VA",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "Harvard University",
    shortName: "Harvard",
    nickname: "Crimson",
    city: "Cambridge",
    state: "MA",
    conference: "Ivy",
    subdivision: "FCS",
  },
  {
    name: "College of the Holy Cross",
    shortName: "Holy Cross",
    nickname: "Crusaders",
    city: "Worcester",
    state: "MA",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Houston Christian University",
    shortName: "Houston Christian",
    nickname: "Huskies",
    city: "Houston",
    state: "TX",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Howard University",
    shortName: "Howard",
    nickname: "Bison",
    city: "Washington",
    state: "DC",
    conference: "MEAC",
    subdivision: "FCS",
  },
  {
    name: "University of Idaho",
    shortName: "Idaho",
    nickname: "Vandals",
    city: "Moscow",
    state: "ID",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "Idaho State University",
    shortName: "Idaho State",
    nickname: "Bengals",
    city: "Pocatello",
    state: "ID",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "Illinois State University",
    shortName: "Illinois State",
    nickname: "Redbirds",
    city: "Normal",
    state: "IL",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "University of the Incarnate Word",
    shortName: "Incarnate Word",
    nickname: "Cardinals",
    city: "San Antonio",
    state: "TX",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Indiana State University",
    shortName: "Indiana State",
    nickname: "Sycamores",
    city: "Terre Haute",
    state: "IN",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "Jackson State University",
    shortName: "Jackson State",
    nickname: "Tigers",
    city: "Jackson",
    state: "MS",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Lafayette College",
    shortName: "Lafayette",
    nickname: "Leopards",
    city: "Easton",
    state: "PA",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Lamar University",
    shortName: "Lamar",
    nickname: "Cardinals",
    city: "Beaumont",
    state: "TX",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Lehigh University",
    shortName: "Lehigh",
    nickname: "Mountain Hawks",
    city: "Bethlehem",
    state: "PA",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Lindenwood University",
    shortName: "Lindenwood",
    nickname: "Lions",
    city: "St. Charles",
    state: "MO",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "Long Island University",
    shortName: "LIU",
    nickname: "Sharks",
    city: "Brookville",
    state: "NY",
    conference: "NEC",
    subdivision: "FCS",
  },
  {
    name: "University of Maine",
    shortName: "Maine",
    nickname: "Black Bears",
    city: "Orono",
    state: "ME",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "Marist University",
    shortName: "Marist",
    nickname: "Red Foxes",
    city: "Poughkeepsie",
    state: "NY",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "McNeese State University",
    shortName: "McNeese",
    nickname: "Cowboys",
    city: "Lake Charles",
    state: "LA",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Mercer University",
    shortName: "Mercer",
    nickname: "Bears",
    city: "Macon",
    state: "GA",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "Merrimack College",
    shortName: "Merrimack",
    nickname: "Warriors",
    city: "North Andover",
    state: "MA",
    conference: "Independent",
    subdivision: "FCS",
  },
  {
    name: "Mississippi Valley State University",
    shortName: "Mississippi Valley State",
    nickname: "Delta Devils",
    city: "Itta Bena",
    state: "MS",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Monmouth University",
    shortName: "Monmouth",
    nickname: "Hawks",
    city: "West Long Branch",
    state: "NJ",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "University of Montana",
    shortName: "Montana",
    nickname: "Grizzlies",
    city: "Missoula",
    state: "MT",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "Montana State University",
    shortName: "Montana State",
    nickname: "Bobcats",
    city: "Bozeman",
    state: "MT",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "Morehead State University",
    shortName: "Morehead State",
    nickname: "Eagles",
    city: "Morehead",
    state: "KY",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "Morgan State University",
    shortName: "Morgan State",
    nickname: "Bears",
    city: "Baltimore",
    state: "MD",
    conference: "MEAC",
    subdivision: "FCS",
  },
  {
    name: "Murray State University",
    shortName: "Murray State",
    nickname: "Racers",
    city: "Murray",
    state: "KY",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "University of New Hampshire",
    shortName: "New Hampshire",
    nickname: "Wildcats",
    city: "Durham",
    state: "NH",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "Nicholls State University",
    shortName: "Nicholls",
    nickname: "Colonels",
    city: "Thibodaux",
    state: "LA",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Norfolk State University",
    shortName: "Norfolk State",
    nickname: "Spartans",
    city: "Norfolk",
    state: "VA",
    conference: "MEAC",
    subdivision: "FCS",
  },
  {
    name: "University of North Alabama",
    shortName: "North Alabama",
    nickname: "Lions",
    city: "Florence",
    state: "AL",
    conference: "UAC",
    subdivision: "FCS",
  },
  {
    name: "North Carolina A&T State University",
    shortName: "North Carolina A&T",
    nickname: "Aggies",
    city: "Greensboro",
    state: "NC",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "North Carolina Central University",
    shortName: "North Carolina Central",
    nickname: "Eagles",
    city: "Durham",
    state: "NC",
    conference: "MEAC",
    subdivision: "FCS",
  },
  {
    name: "University of North Dakota",
    shortName: "North Dakota",
    nickname: "Fighting Hawks",
    city: "Grand Forks",
    state: "ND",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "North Dakota State University",
    shortName: "North Dakota State",
    nickname: "Bison",
    city: "Fargo",
    state: "ND",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "Northern Arizona University",
    shortName: "Northern Arizona",
    nickname: "Lumberjacks",
    city: "Flagstaff",
    state: "AZ",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "University of Northern Colorado",
    shortName: "Northern Colorado",
    nickname: "Bears",
    city: "Greeley",
    state: "CO",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "University of Northern Iowa",
    shortName: "Northern Iowa",
    nickname: "Panthers",
    city: "Cedar Falls",
    state: "IA",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "Northwestern State University",
    shortName: "Northwestern State",
    nickname: "Demons",
    city: "Natchitoches",
    state: "LA",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "University of Pennsylvania",
    shortName: "Penn",
    nickname: "Quakers",
    city: "Philadelphia",
    state: "PA",
    conference: "Ivy",
    subdivision: "FCS",
  },
  {
    name: "Portland State University",
    shortName: "Portland State",
    nickname: "Vikings",
    city: "Portland",
    state: "OR",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "Prairie View A&M University",
    shortName: "Prairie View A&M",
    nickname: "Panthers",
    city: "Prairie View",
    state: "TX",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Presbyterian College",
    shortName: "Presbyterian",
    nickname: "Blue Hose",
    city: "Clinton",
    state: "SC",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "Princeton University",
    shortName: "Princeton",
    nickname: "Tigers",
    city: "Princeton",
    state: "NJ",
    conference: "Ivy",
    subdivision: "FCS",
  },
  {
    name: "University of Rhode Island",
    shortName: "Rhode Island",
    nickname: "Rams",
    city: "Kingston",
    state: "RI",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "University of Richmond",
    shortName: "Richmond",
    nickname: "Spiders",
    city: "Richmond",
    state: "VA",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Robert Morris University",
    shortName: "Robert Morris",
    nickname: "Colonials",
    city: "Moon Township",
    state: "PA",
    conference: "NEC",
    subdivision: "FCS",
  },
  {
    name: "Sacred Heart University",
    shortName: "Sacred Heart",
    nickname: "Pioneers",
    city: "Fairfield",
    state: "CT",
    conference: "Independent",
    subdivision: "FCS",
  },
  {
    name: "Saint Francis University",
    shortName: "Saint Francis",
    nickname: "Red Flash",
    city: "Loretto",
    state: "PA",
    conference: "NEC",
    subdivision: "FCS",
  },
  {
    name: "University of St. Thomas",
    shortName: "St. Thomas",
    nickname: "Tommies",
    city: "Saint Paul",
    state: "MN",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "Samford University",
    shortName: "Samford",
    nickname: "Bulldogs",
    city: "Birmingham",
    state: "AL",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "University of San Diego",
    shortName: "San Diego",
    nickname: "Toreros",
    city: "San Diego",
    state: "CA",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "South Carolina State University",
    shortName: "South Carolina State",
    nickname: "Bulldogs",
    city: "Orangeburg",
    state: "SC",
    conference: "MEAC",
    subdivision: "FCS",
  },
  {
    name: "University of South Dakota",
    shortName: "South Dakota",
    nickname: "Coyotes",
    city: "Vermillion",
    state: "SD",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "South Dakota State University",
    shortName: "South Dakota State",
    nickname: "Jackrabbits",
    city: "Brookings",
    state: "SD",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "Southeast Missouri State University",
    shortName: "Southeast Missouri State",
    nickname: "Redhawks",
    city: "Cape Girardeau",
    state: "MO",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "Southeastern Louisiana University",
    shortName: "Southeastern Louisiana",
    nickname: "Lions",
    city: "Hammond",
    state: "LA",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Southern University",
    shortName: "Southern",
    nickname: "Jaguars",
    city: "Baton Rouge",
    state: "LA",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Southern Illinois University Carbondale",
    shortName: "Southern Illinois",
    nickname: "Salukis",
    city: "Carbondale",
    state: "IL",
    conference: "MVFC",
    subdivision: "FCS",
  },
  {
    name: "Southern Utah University",
    shortName: "Southern Utah",
    nickname: "Thunderbirds",
    city: "Cedar City",
    state: "UT",
    conference: "UAC",
    subdivision: "FCS",
  },
  {
    name: "Stephen F. Austin State University",
    shortName: "Stephen F. Austin",
    nickname: "Lumberjacks",
    city: "Nacogdoches",
    state: "TX",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Stetson University",
    shortName: "Stetson",
    nickname: "Hatters",
    city: "DeLand",
    state: "FL",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "Stonehill College",
    shortName: "Stonehill",
    nickname: "Skyhawks",
    city: "Easton",
    state: "MA",
    conference: "NEC",
    subdivision: "FCS",
  },
  {
    name: "Stony Brook University",
    shortName: "Stony Brook",
    nickname: "Seawolves",
    city: "Stony Brook",
    state: "NY",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "Tarleton State University",
    shortName: "Tarleton State",
    nickname: "Texans",
    city: "Stephenville",
    state: "TX",
    conference: "UAC",
    subdivision: "FCS",
  },
  {
    name: "Tennessee State University",
    shortName: "Tennessee State",
    nickname: "Tigers",
    city: "Nashville",
    state: "TN",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "Tennessee Technological University",
    shortName: "Tennessee Tech",
    nickname: "Golden Eagles",
    city: "Cookeville",
    state: "TN",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "Texas Southern University",
    shortName: "Texas Southern",
    nickname: "Tigers",
    city: "Houston",
    state: "TX",
    conference: "SWAC",
    subdivision: "FCS",
  },
  {
    name: "Towson University",
    shortName: "Towson",
    nickname: "Tigers",
    city: "Towson",
    state: "MD",
    conference: "CAA",
    subdivision: "FCS",
  },
  {
    name: "University of California, Davis",
    shortName: "UC Davis",
    nickname: "Aggies",
    city: "Davis",
    state: "CA",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "University of Tennessee at Martin",
    shortName: "UT Martin",
    nickname: "Skyhawks",
    city: "Martin",
    state: "TN",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "Utah Tech University",
    shortName: "Utah Tech",
    nickname: "Trailblazers",
    city: "St. George",
    state: "UT",
    conference: "UAC",
    subdivision: "FCS",
  },
  {
    name: "University of Texas Rio Grande Valley",
    shortName: "UTRGV",
    nickname: "Vaqueros",
    city: "Edinburg",
    state: "TX",
    conference: "Southland",
    subdivision: "FCS",
  },
  {
    name: "Valparaiso University",
    shortName: "Valparaiso",
    nickname: "Beacons",
    city: "Valparaiso",
    state: "IN",
    conference: "PFL",
    subdivision: "FCS",
  },
  {
    name: "Villanova University",
    shortName: "Villanova",
    nickname: "Wildcats",
    city: "Villanova",
    state: "PA",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Virginia Military Institute",
    shortName: "VMI",
    nickname: "Keydets",
    city: "Lexington",
    state: "VA",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "Wagner College",
    shortName: "Wagner",
    nickname: "Seahawks",
    city: "New York",
    state: "NY",
    conference: "NEC",
    subdivision: "FCS",
  },
  {
    name: "Weber State University",
    shortName: "Weber State",
    nickname: "Wildcats",
    city: "Ogden",
    state: "UT",
    conference: "Big Sky",
    subdivision: "FCS",
  },
  {
    name: "Western Carolina University",
    shortName: "Western Carolina",
    nickname: "Catamounts",
    city: "Cullowhee",
    state: "NC",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "Western Illinois University",
    shortName: "Western Illinois",
    nickname: "Leathernecks",
    city: "Macomb",
    state: "IL",
    conference: "Big South-OVC",
    subdivision: "FCS",
  },
  {
    name: "College of William & Mary",
    shortName: "William & Mary",
    nickname: "Tribe",
    city: "Williamsburg",
    state: "VA",
    conference: "Patriot",
    subdivision: "FCS",
  },
  {
    name: "Wofford College",
    shortName: "Wofford",
    nickname: "Terriers",
    city: "Spartanburg",
    state: "SC",
    conference: "SoCon",
    subdivision: "FCS",
  },
  {
    name: "Yale University",
    shortName: "Yale",
    nickname: "Bulldogs",
    city: "New Haven",
    state: "CT",
    conference: "Ivy",
    subdivision: "FCS",
  },
  {
    name: "Youngstown State University",
    shortName: "Youngstown State",
    nickname: "Penguins",
    city: "Youngstown",
    state: "OH",
    conference: "MVFC",
    subdivision: "FCS",
  },
];
