package app.zoneblitz.gamesimulator.event;

/** Coarse-grained penalty classification used by {@link PlayEvent.Penalty}. */
public enum PenaltyType {
  FALSE_START,
  OFFSIDE,
  ENCROACHMENT,
  NEUTRAL_ZONE_INFRACTION,
  DELAY_OF_GAME,
  HOLDING_OFFENSE,
  HOLDING_DEFENSE,
  PASS_INTERFERENCE_OFFENSE,
  PASS_INTERFERENCE_DEFENSE,
  ILLEGAL_FORMATION,
  ILLEGAL_USE_OF_HANDS,
  ROUGHING_THE_PASSER,
  ROUGHING_THE_KICKER,
  FACE_MASK,
  UNNECESSARY_ROUGHNESS,
  UNSPORTSMANLIKE_CONDUCT,
  TAUNTING,
  ILLEGAL_BLOCK_IN_THE_BACK,
  CLIPPING,
  HORSE_COLLAR,
  ILLEGAL_CONTACT,
  ILLEGAL_SHIFT,
  ILLEGAL_MOTION,
  TWELVE_MEN_ON_FIELD,
  OTHER
}
