import { CALIBRATION_SEED } from "./calibration-seed.ts";

// Fixed set of seeds the harness runs against on every invocation.
// The anchor (first entry) is the one also materialized on disk in
// ./fixtures/calibration-league.json for human debugging — it's
// regenerated by generate-fixture.ts but consumed purely in-memory
// here so the harness always exercises the current generator code.
//
// Every additional seed widens the surface area a single-seed overfit
// can hide in. 8 derived leagues × 1344 games = ~11k games per run
// and ~80s of wall time — well within the nightly 30-minute budget.
export const CALIBRATION_SEEDS: readonly number[] = [
  CALIBRATION_SEED,
  0xA11CE_11,
  0xDEADBEEF,
  0xFACEFEED,
  0xBADDCAFE,
  0xC0FFEE42,
  0xFEEDFACE,
  0x0CABBA6E,
] as const;
