import { runCalibration } from "./harness.ts";
import { formatReport } from "./format-report.ts";
import { simulateGame } from "../simulate-game.ts";
import { generateCalibrationLeague } from "./generate-calibration-league.ts";
import { CALIBRATION_SEEDS } from "./calibration-seeds.ts";

// Generate every calibration league at runtime and run the harness
// against each. A single-seed pass can hide real drift on every
// other rng path; eight seeds tightens the gate without bloating the
// repo with a JSON fixture per seed. The anchor fixture on disk
// (./fixtures/calibration-league.json) is purely a human debugging
// aid — it is regenerated by generate-fixture.ts but not read here.
const bandPath = new URL(
  "../../../../data/bands/team-game.json",
  import.meta.url,
);

const bandJson = await Deno.readTextFile(bandPath);

let allPassed = true;
const summary: { seed: number; passed: number; total: number }[] = [];

for (const seed of CALIBRATION_SEEDS) {
  const league = generateCalibrationLeague({ seed });
  const report = runCalibration({
    bandJson,
    league,
    simulate: simulateGame,
  });

  console.log(`=== seed=0x${seed.toString(16)} ===`);
  console.log(formatReport(report));
  console.log("");

  const passCount = report.results.length - report.failures.length;
  summary.push({
    seed,
    passed: passCount,
    total: report.results.length,
  });
  if (!report.passed) allPassed = false;
}

console.log("=== Multi-seed summary ===");
for (const row of summary) {
  const status = row.passed === row.total ? "PASS" : "FAIL";
  console.log(
    `${status} seed=0x${row.seed.toString(16)}: ${row.passed}/${row.total}`,
  );
}

if (!allPassed) {
  Deno.exit(1);
}
