version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - devcontainer.env
  
  db:
    image: postgres:16
    env_file:
      - devcontainer.env
  
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - devcontainer.env
    depends_on:
      - db
