version: "3"

services:
  dev:
    image: "mcr.microsoft.com/devcontainers/base:jammy"
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - devcontainer.env
  
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
  
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - devcontainer.env
    depends_on:
      - db
