version: "3"

services:
  dev:
    image: "mcr.microsoft.com/devcontainers/base:jammy"
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
  
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: "postgres://postgres:example@db:5432/postgres?sslmode=disable"
    depends_on:
      - db
