version: "3"

services:
  dev:
    image: "mcr.microsoft.com/devcontainers/base:jammy"
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
    ports:

