/**
 * The 32 default fictional teams, organized into 2 conferences and 8 divisions.
 * Each team is a knock-off inspired by a real NFL franchise with a unique identity.
 */
export interface DefaultTeam {
  name: string;
  city: string;
  abbreviation: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  conference: string;
  division: string;
}

export const DEFAULT_TEAMS: DefaultTeam[] = [
  // === ATLANTIC FOOTBALL CONFERENCE (AFC) ===

  // AFC East
  {
    name: "Minutemen",
    city: "Boston",
    abbreviation: "BOS",
    primaryColor: "#0B2240",
    secondaryColor: "#C41230",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC East",
  },
  {
    name: "Sharks",
    city: "Miami",
    abbreviation: "MIA",
    primaryColor: "#006B70",
    secondaryColor: "#FF6B35",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC East",
  },
  {
    name: "Aviators",
    city: "New York",
    abbreviation: "NYA",
    primaryColor: "#1A472A",
    secondaryColor: "#FFFFFF",
    accentColor: "#C8AA6E",
    conference: "AFC",
    division: "AFC East",
  },
  {
    name: "Thunderbolts",
    city: "Buffalo",
    abbreviation: "BUF",
    primaryColor: "#00338D",
    secondaryColor: "#C8102E",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC East",
  },

  // AFC North
  {
    name: "Ironworkers",
    city: "Pittsburgh",
    abbreviation: "PIT",
    primaryColor: "#2E2E2E",
    secondaryColor: "#FFB612",
    accentColor: "#C41230",
    conference: "AFC",
    division: "AFC North",
  },
  {
    name: "Monarchs",
    city: "Baltimore",
    abbreviation: "BAL",
    primaryColor: "#2B1A6E",
    secondaryColor: "#C8AA6E",
    accentColor: "#000000",
    conference: "AFC",
    division: "AFC North",
  },
  {
    name: "Bulldogs",
    city: "Cleveland",
    abbreviation: "CLE",
    primaryColor: "#6B3410",
    secondaryColor: "#FF6B00",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC North",
  },
  {
    name: "Sabercats",
    city: "Cincinnati",
    abbreviation: "CIN",
    primaryColor: "#FB4F14",
    secondaryColor: "#000000",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC North",
  },

  // AFC South
  {
    name: "Roughnecks",
    city: "Houston",
    abbreviation: "HOU",
    primaryColor: "#03202F",
    secondaryColor: "#C41230",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC South",
  },
  {
    name: "Racers",
    city: "Indianapolis",
    abbreviation: "IND",
    primaryColor: "#003A70",
    secondaryColor: "#FFFFFF",
    accentColor: "#A5ACAF",
    conference: "AFC",
    division: "AFC South",
  },
  {
    name: "Gators",
    city: "Jacksonville",
    abbreviation: "JAX",
    primaryColor: "#006778",
    secondaryColor: "#D7A33D",
    accentColor: "#000000",
    conference: "AFC",
    division: "AFC South",
  },
  {
    name: "Volunteers",
    city: "Nashville",
    abbreviation: "NSH",
    primaryColor: "#4B92DB",
    secondaryColor: "#C41230",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC South",
  },

  // AFC West
  {
    name: "Wranglers",
    city: "Denver",
    abbreviation: "DEN",
    primaryColor: "#FC4C02",
    secondaryColor: "#002244",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC West",
  },
  {
    name: "Outlaws",
    city: "Las Vegas",
    abbreviation: "LVG",
    primaryColor: "#A5ACAF",
    secondaryColor: "#000000",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC West",
  },
  {
    name: "Captains",
    city: "Los Angeles",
    abbreviation: "LAC",
    primaryColor: "#0080C6",
    secondaryColor: "#FFC20E",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC West",
  },
  {
    name: "Trailblazers",
    city: "Kansas City",
    abbreviation: "KCT",
    primaryColor: "#E31837",
    secondaryColor: "#FFB81C",
    accentColor: "#FFFFFF",
    conference: "AFC",
    division: "AFC West",
  },

  // === NATIONAL FOOTBALL CONFERENCE (NFC) ===

  // NFC East
  {
    name: "Sentinels",
    city: "Washington",
    abbreviation: "WAS",
    primaryColor: "#5A1414",
    secondaryColor: "#FFB612",
    accentColor: "#FFFFFF",
    conference: "NFC",
    division: "NFC East",
  },
  {
    name: "Titans",
    city: "New York",
    abbreviation: "NYT",
    primaryColor: "#0B2265",
    secondaryColor: "#C41230",
    accentColor: "#A5ACAF",
    conference: "NFC",
    division: "NFC East",
  },
  {
    name: "Liberty Bells",
    city: "Philadelphia",
    abbreviation: "PHI",
    primaryColor: "#004C54",
    secondaryColor: "#A5ACAF",
    accentColor: "#000000",
    conference: "NFC",
    division: "NFC East",
  },
  {
    name: "Lone Stars",
    city: "Dallas",
    abbreviation: "DAL",
    primaryColor: "#003A70",
    secondaryColor: "#A5ACAF",
    accentColor: "#FFFFFF",
    conference: "NFC",
    division: "NFC East",
  },

  // NFC North
  {
    name: "Lumberjacks",
    city: "Green Bay",
    abbreviation: "GBL",
    primaryColor: "#204E32",
    secondaryColor: "#FFB612",
    accentColor: "#FFFFFF",
    conference: "NFC",
    division: "NFC North",
  },
  {
    name: "Grizzlies",
    city: "Chicago",
    abbreviation: "CHI",
    primaryColor: "#0B162A",
    secondaryColor: "#C83803",
    accentColor: "#FFFFFF",
    conference: "NFC",
    division: "NFC North",
  },
  {
    name: "Voyageurs",
    city: "Minnesota",
    abbreviation: "MIN",
    primaryColor: "#4F2683",
    secondaryColor: "#FFC62F",
    accentColor: "#FFFFFF",
    conference: "NFC",
    division: "NFC North",
  },
  {
    name: "Pistons",
    city: "Detroit",
    abbreviation: "DET",
    primaryColor: "#0076B6",
    secondaryColor: "#A5ACAF",
    accentColor: "#000000",
    conference: "NFC",
    division: "NFC North",
  },

  // NFC South
  {
    name: "Krewe",
    city: "New Orleans",
    abbreviation: "NOR",
    primaryColor: "#D3BC8D",
    secondaryColor: "#101820",
    accentColor: "#FFFFFF",
    conference: "NFC",
    division: "NFC South",
  },
  {
    name: "Firebirds",
    city: "Atlanta",
    abbreviation: "ATL",
    primaryColor: "#A71930",
    secondaryColor: "#000000",
    accentColor: "#A5ACAF",
    conference: "NFC",
    division: "NFC South",
  },
  {
    name: "Hurricanes",
    city: "Tampa Bay",
    abbreviation: "TBH",
    primaryColor: "#BD1C36",
    secondaryColor: "#3E3A35",
    accentColor: "#FF7900",
    conference: "NFC",
    division: "NFC South",
  },
  {
    name: "Prowlers",
    city: "Charlotte",
    abbreviation: "CLT",
    primaryColor: "#0085CA",
    secondaryColor: "#000000",
    accentColor: "#A5ACAF",
    conference: "NFC",
    division: "NFC South",
  },

  // NFC West
  {
    name: "Prospectors",
    city: "San Francisco",
    abbreviation: "SFP",
    primaryColor: "#AA0000",
    secondaryColor: "#B3995D",
    accentColor: "#FFFFFF",
    conference: "NFC",
    division: "NFC West",
  },
  {
    name: "Condors",
    city: "Los Angeles",
    abbreviation: "LAR",
    primaryColor: "#003594",
    secondaryColor: "#FFD100",
    accentColor: "#FFFFFF",
    conference: "NFC",
    division: "NFC West",
  },
  {
    name: "Cascaders",
    city: "Seattle",
    abbreviation: "SEA",
    primaryColor: "#002244",
    secondaryColor: "#69BE28",
    accentColor: "#A5ACAF",
    conference: "NFC",
    division: "NFC West",
  },
  {
    name: "Sidewinders",
    city: "Arizona",
    abbreviation: "ARI",
    primaryColor: "#97233F",
    secondaryColor: "#000000",
    accentColor: "#FFB612",
    conference: "NFC",
    division: "NFC West",
  },
];
