name: CI

on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run application tests in development container
        uses: devcontainers/ci@v0.3
        with:
          imageName: mcr.microsoft.com/devcontainers/base:jammy
          runCmd: deno task test
