name: CI

on: push

env:
  DEVCONTAINER_PLATFORM: linux/arm64

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run application tests in development container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: deno task test
