name: CI

on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run application tests in development container
        uses: devcontainers/ci@v0.3
        with:
          imageName: Tiernebre/zone-blitz-dev
          cacheFrom: Tiernebre/zone-blitz-dev
          push: always
          runCmd: make ci-build
          platform: arm64
